# coding: utf-8

"""
    LOCKSS Metadata Extraction Service REST API

    API of the LOCKSS Metadata Extraction REST Service  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lockss_metadata_extractor
from lockss_metadata_extractor.api.mdupdates_api import MdupdatesApi  # noqa: E501
from lockss_metadata_extractor.rest import ApiException


class TestMdupdatesApi(unittest.TestCase):
    """MdupdatesApi unit test stubs"""

    def setUp(self):
        self.api = lockss_metadata_extractor.api.mdupdates_api.MdupdatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_mdupdates(self):
        """Test case for delete_mdupdates

        Delete all of the currently queued and active jobs  # noqa: E501
        """
        pass

    def test_delete_mdupdates_jobid(self):
        """Test case for delete_mdupdates_jobid

        Delete a job  # noqa: E501
        """
        pass

    def test_get_mdupdates(self):
        """Test case for get_mdupdates

        Get a list of currently active jobs  # noqa: E501
        """
        pass

    def test_get_mdupdates_jobid(self):
        """Test case for get_mdupdates_jobid

        Get a job  # noqa: E501
        """
        pass

    def test_post_mdupdates(self):
        """Test case for post_mdupdates

        Perform an AU metadata update operation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
