# coding: utf-8

"""
    LOCKSS Metadata Extraction Service REST API

    API of the LOCKSS Metadata Extraction REST Service  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lockss_metadata_extractor
from lockss_metadata_extractor.models.job_page_info import JobPageInfo  # noqa: E501
from lockss_metadata_extractor.rest import ApiException


class TestJobPageInfo(unittest.TestCase):
    """JobPageInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobPageInfo(self):
        """Test JobPageInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lockss_metadata_extractor.models.job_page_info.JobPageInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
